# agents/validator.py
"""
Validator module for Lua code syntax checking and cleaning.
Uses luaparser to parse, validate, and reconstruct clean Lua code.
"""
import sys
import os

# Pastikan path parent bisa diakses jika diperlukan, 
# tapi karena luaparser adalah library eksternal, kita gunakan langsung.
try:
    from luaparser import ast
except ImportError:
    print("[!] Error: Module 'luaparser' not found.")
    print("    Please install it by running: pip install luaparser")
    raise

def validate_and_reconstruct_lua(lua_code: str) -> str | None:
    """
    Parses the raw Lua code string into an Abstract Syntax Tree (AST),
    validates that there are no syntax errors, and then reconstructs 
    back into a clean Lua string.
    
    Args:
        lua_code (str): The raw Lua code string generated by the LLM.
        
    Returns:
        str: Cleaned Lua code if valid.
        None: If syntax is invalid or reconstruction fails.
    """
    try:
        # 1. Parse to AST
        # This step will raise an exception if there are syntax errors
        tree = ast.parse(lua_code)
        
        # 2. Convert AST back to Lua string
        # This effectively normalizes the code (fixes indentation, spacing, etc.)
        clean_code = ast.to_lua_source(tree)
        
        return clean_code
        
    except Exception as e:
        # Log the error internally but return None to signal failure
        # We don't want to crash the whole agent loop
        print(f"[DEBUG] Validator: Syntax error detected in generated code.\n"
              f"Error details: {e}")
        return None

# Optional: Simple test runner if you run this file directly
if __name__ == "__main__":
    test_code = """
local my_lib = require("my_lib")
function sum(a, b)
    return a + b
end
    """
    
    print("Testing Validator...")
    print(f"Original:\n{test_code.strip()}\n")
    
    result = validate_and_reconstruct_lua(test_code)
    
    if result:
        print("--- Validation Successful ---")
        print(f"Clean Code:\n{result}")
    else:
        print("--- Validation Failed ---")
        print("The code contained syntax errors.")
